version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      # install internal SDK (Java)
      - cd "$CODEBUILD_SRC_DIR_SDK"
      # - >
      #   mvn org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file --batch-mode
      #   -Dfile=cloudformation-2.5.11.jar -DgroupId=software.amazon.awssdk -DartifactId=<Your POM artifact ID> -Dversion=<Your POM artifact Version> -Dpackaging=jar
      - cd "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-component"
      - mvn clean verify install --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-theme"
      - mvn clean verify -X --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-component/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-theme/rpdk.log"
