version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.7
    commands:
      - pip install pre-commit cloudformation-cli-java-plugin
      - pip install --upgrade 'PyYAML>=5.1,<6.0'
      - pip install --upgrade 'six==1.15.0'
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-component"
      - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
      - ls
      - cd "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-theme"
      - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
      - ls
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-component/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-amplifyuibuilder-theme/rpdk.log"
